# Generated by Django 5.0.6 on 2024-05-25 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 25, 20, 33, 6, 215124)),
            preserve_default=False,
        ),
    ]
